# Generated by Django 4.1.3 on 2022-11-13 15:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default="+79153177473", max_length=128, region=None),
            preserve_default=False,
        ),
    ]
