# Generated by Django 4.1.3 on 2022-11-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_corporate',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
